### ISSUE TITLE
Freedesktop SDK 19.08 EOL

### ISSUE THREAD

**Issue by mrmstn** [flathub/org.zaproxy.ZAP#5]
Hi there,

I'm not quite sure if I'm in the right place here, but I saw to following message during my update procedures
```
Info: org.freedesktop.Platform//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Applications using this runtime:
   org.zaproxy.ZAP
Info: org.freedesktop.Platform.GL.default//19.08 is end-of-life, with reason:
   The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
```

**Comment by thc202** [comment]
This is the right place, thank you!

**Comment by kingthorin** [comment]
- https://docs.flatpak.org/en/latest/available-runtimes.html
- https://gitlab.com/freedesktop-sdk/freedesktop-sdk/

**Comment by thc202** [comment]
Just finished building with 20.08, runs fine.

**Comment by kingthorin** [comment]
Is there a 21.08? Their releases seem inconsistent in naming vs attachments/details.

**Comment by thc202** [comment]
I picked 20.08 because of the release information in https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/wikis/Releases though I guess 21.08 should be already released.

**Comment by thc202** [comment]
Trying with newer version...

**Comment by kingthorin** [comment]
https://twitter.com/kingthorin_rm/status/1439567796111912964
